## Ansible playbook for installing common packages.
## This is a playbook YAML file for the Ansible provider
## Modified from @author Jeff Geerling (2015).
---
- name: Update apt cache if needed.
  become_user: root
  apt:
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time }}"
  become: yes
- name: Ensure basic packages are installed
  become_user: root
  apt:
    name: ['gcc', 'g++', 'curl','wget', 'landscape-common', 'software-properties-common', 'unzip', 'git', 'make', 'automake', 'autoconf', 'libreadline-dev','libncurses-dev', 'libssl-dev', 'libyaml-dev', 'libxslt-dev', 'libffi-dev','libtool', 'unixodbc-dev']
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"
  tags: common
  become: yes
# Could not import python modules: apt, apt_pkg before python3-apt package which is done at the previous task.
- name: Ensure apt-transport-https is installed.
  apt:
    name: apt-transport-https
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"
  tags: common
  become: yes
# A task for adding the credentials
- name: Should have credentials dir
  become_user: root
  file:
    path: ~/credentials
    state: directory
  tags: common
- name: install zsh and friends
  package:
    name: ['git-core','zsh']
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"
  become: yes
  tags: common
# A task for installing Docker and its companion
- name: install Docker and friends
  become_user: root
  package:
    name: ['docker']
    state: latest
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"
  become: yes
  tags: common