# Maven task defaults
---
- name: Fetch latest release version of Kotlin.
  uri:
    url: https://api.github.com/repos/JetBrains/kotlin/releases/latest
    body_format: json
    return_content: true
  register: json_response
  tags: kotlin

# Kotlin release directory
- name: Ensure Kotlin release directory exists
  become: true
  file:
    path: /opt/kotlin-{{ kotlin_version }}
    state: directory

# Download and unzip Kotlin version
- name: Download and unzip latest Kotlin version.
  become: true
  unarchive:
    src: "{{ Kotlin_source }}"
    dest: /opt/kotlin-{{ kotlin_version }}
    remote_src: true

- name: Create Kotlin symlinks
  file:
    src: /opt/kotlin-{{ kotlin_version }}/kotlinc/bin/{{ kotlin_bin }}
    dest: /usr/local/bin/{{ item.dest }}
    state: link
    force: true
  with_items:
    - { src: 'kotlin', dest: 'kotlin' }
    - { src: 'kotlinc', dest: 'kotlinc' }
    - { src: 'kotlinc-js', dest: 'kotlinc-js' }
    - { src: 'kotlinc-jvm', dest: 'kotlinc-jvm' }
    - { src: 'kotlin-compiler', dest: 'kotlin-compiler' }
    - { src: 'kotlin-dce-js', dest: 'kotlin-dce-js' }
