---
- name: add an apt ubuntu/erlang_solutions signing key
  apt_key:
    url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    state: present

- name: add erlang-solutions repository into sources list
  apt_repository:
    repo: deb https://packages.erlang-solutions.com/ubuntu xenial contrib
    state: present

- name: install packages
  apt:
    name: ['erlang', 'elixir']
    state: present
    update_cache: yes
    cache_valid_time: 86400

- name: install PostgreSQL
  apt:
    name: [' postgresql', 'python-psycopg2','postgresql-contrib','postgresql-server-dev-9.5 ']
    state: present
    update_cache: yes
    cache_valid_time: 86400