---
# apt_key to add repository keys
# MongoDB public GPG Key to be imported
- name: Import the public key used by the package management system
    apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: 7F0CEB10
      state: present

# Adding MongoDB apt_repository
- name: Add MongoDB repository
  apt_repository:
    repo: 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen'
    state: present
